### ISSUE TITLE
Site-specific ADOs aren't actually site-specific

### ISSUE THREAD

**Issue by jarrybarber** [dapogon/cellcoal#6]
In the AllelicDropout function, alleleADOrateSite is resampled for each (cell,site) iteration rather than being sampled once and stored for reuse across all cell genotypes. This results in the ADO rates being about the same across all sites.

If helpful, I have attached a file with a fixed version of the function.
[fix.zip](https://github.com/user-attachments/files/16898955/fix.zip)

**Comment by dapogon** [comment]
Hi Jerry, thank you for letting me know. I will try to find some time soon to fix this. Best, D

---
David Posada
CINBIO
Universidade de Vigo
36310 Vigo
Spain

Phone: +34 986 812038
Cell: +34 647 343300
Email: ***@***.***
Web: http://darwin.uvigo.es
________________________________
From: jarrybarber ***@***.***>
Sent: Thursday, September 5, 2024 8:50 PM
To: dapogon/cellcoal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dapogon/cellcoal] Site-specific ADOs aren't actually site-specific (Issue #6)


In the AllelicDropout function, alleleADOrateSite is resampled for each (cell,site) iteration rather than being sampled once and stored for reuse across all cell genotypes. This results in the ADO rates being about the same across all sites.

If helpful, I have attached a file with a fixed version of the function.
fix.zip<https://urldefense.com/v3/__https://github.com/user-attachments/files/16898955/fix.zip__;!!D9dNQwwGXtA!THNx4jumo8_pAGomVUv0ibneLlrUgXIyLbwlL0I415SAxYLFjy4lecLeEa2Q1oyFMYLbGJWOwo5oF_MbDbz3H0HE$>

**Comment by dapogon** [comment]
Just fixed, thank you. I guess at that point I had a random bias (MDA) in my mind, but this way is more flexible
